services:
    # MongoDB instances for each service
    user-db:
        image: mongo:7.0
        restart: always
        environment:
            MONGO_INITDB_DATABASE: smart_library_users
        volumes:
            - mongo_user_data:/data/db
        networks:
            - slnet

    book-db:
        image: mongo:7.0
        restart: always
        environment:
            MONGO_INITDB_DATABASE: smart_library_books
        volumes:
            - mongo_book_data:/data/db
        networks:
            - slnet

    loan-db:
        image: mongo:7.0
        restart: always
        environment:
            MONGO_INITDB_DATABASE: smart_library_loans
        volumes:
            - mongo_loan_data:/data/db
        networks:
            - slnet

    user-service:
        image: nahid/smartlibrary:user-service
        build: ./user-service
        environment:
            MONGODB_URI: mongodb://user-db:27017/smart_library_users
            NODE_ENV: development
        depends_on:
            - user-db
        networks:
            - slnet

    book-service:
        image: nahid/smartlibrary:book-service
        build: ./book-service
        environment:
            MONGODB_URI: mongodb://book-db:27017/smart_library_books
            NODE_ENV: development
        depends_on:
            - book-db
        networks:
            - slnet

    loan-service:
        image: nahid/smartlibrary:loan-service
        build: ./loan-service
        environment:
            USER_SERVICE_URL: http://user-service:8081/api
            BOOK_SERVICE_URL: http://book-service:8082/api
            NODE_ENV: development
            MONGODB_URI: mongodb://loan-db:27017/smart_library_loans
        depends_on:
            - user-service
            - book-service
            - loan-db
        networks:
            - slnet

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/smart-library.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - user-service
            - book-service
            - loan-service
        networks:
            - slnet

networks:
    slnet:
        driver: bridge

volumes:
    mongo_user_data:
    mongo_book_data:
    mongo_loan_data:
